### ISSUE TITLE
LRZip support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nakijun/peazip#149]
```
Hi;
LRZip recently added a library 
(http://ck.kolivas.org/apps/lrzip/lrzip-0.611/WHATS-NEW) allowing LRZIP 
functionality to be added in other programs.
PeaZip, if they added this feature, would be windows users' only portal to this 
strange new compression technology.
I'd really appreciate it, I'm sure I'm not the only one.
```

Original issue reported on code.google.com by `mnc....@gmail.com` on 14 Mar 2012 at 2:01
- Merged into: #19

**Comment by giovariot** [comment]
any chance to see lrzip format added to peazip? it's quite a useuful compression protocol, especially for big disk images

**Comment by 9001** [comment]
late to the party, but wanted to mention that I've found zstd with `--long=31` to do a much better job than lrzip for that same usecase, especially combined with `-T0 -19`. So give that a try if you haven't 👍

**Comment by giovariot** [comment]
Have you compared zstd --long=31 with the -U option in lrzip? Coz I've done tests in the past and the deduplication window is unlimited in lrzip while it's limited in size on zstd.

I don't have the exact data right now but I remember compressing a 128gb disk image from an old disk which had 3 versions of windows installed into a 20-something gb file, while zstd only compressed it to a 30gb size.

Also: lrzip-next included support for zstd compression after the deduplication process as it works really well on the already deduplicated data but for really large windows zstd can't do the same.

Somewhere on the zstd GitHub page there's should be a request I did there to add support for unlimited deduplication support as per lrzip and the results of different test using also the option you suggested.

**Comment by 9001** [comment]
Guess you're working with more redundant images than I am hehe

True, zstd currently maxes out at 2 GiB with long=31. At least [the issue](https://github.com/facebook/zstd/issues/3062) you mentioned confirms that higher values are on the roadmap, and now I'm looking forward to that as well :>
